COIN_SYMBOLS = ["BTCUSDT", "ETHUSDT", "BNBUSDT", "USDTTRY", "PAXGTRY"]
CANDLE_PEROIDS = ["1d", "4h", "1h", "15m", "5m"]

CANDLE_LIMIT = 1000

RSI_LENGTH = 14
STOCHRSI_RSI_LENGTH = 5
STOCHRSI_STOCH_LENGTH = 5
STOCHRSI_SMOOTH_K = 5
STOCHRSI_SMOOTH_D = 5
MA_LENGTHS = [25, 50, 200]
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9
BOLL_LENGTH = 20
BOLL_STD = 2

BINANCE_COMISSION_RATE = 0.1 / 100

API_KEY = ""
API_SECRET = ""
